name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Arch Linux Package(s)
        run: |
          pacman-key --init
          pacman -Syu git expac --noconfirm

          echo Workspace: $GITHUB_WORKSPACE
          ls -lha $GITHUB_WORKSPACE

          useradd -m -G wheel -s /bin/bash build
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/00_wheel

          cd /home/build
          sudo -u build git clone https://aur.archlinux.org/aurutils
          cd aurutils
          sudo -u build makepkg -si --noconfirm
          cd ..

          curl -LO https://github.com/$GITHUB_REPOSITORY/releases/download/repository/custom.db
          curl -LO https://github.com/$GITHUB_REPOSITORY/releases/download/repository/custom.files

          cd $GITHUB_WORKSPACE
          sudo -u build ./new_build.sh
