name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Prepare environment
        run: |
          cat << EOF >> /etc/pacman.conf
          [custom]
          SigLevel = Optional TrustAll
          Server = $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/current
          EOF

          pacman-key --init
          pacman -Syu git expac devtools --noconfirm

          echo Workspace: $GITHUB_WORKSPACE
          ls -lha $GITHUB_WORKSPACE

          useradd -m -G wheel -s /bin/bash build
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/00_wheel

          cd /home/build
          sudo -u build git clone https://aur.archlinux.org/aurutils
          cd aurutils
          sudo -u build makepkg -si --noconfirm
          cd ..

          dbus-uuidgen --ensure=/etc/machine-id

          sed -i "s/en_US de_DE/en_US/g" /usr/bin/mkarchroot

          CHROOT=/buildchroot
          mkdir $CHROOT
          mkarchroot $CHROOT/root base-devel

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download repository database
        run: |
          cd $GITHUB_WORKSPACE
          curl -LO "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/current/custom.db"
          curl -LO "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/current/custom.files"
          echo "URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/current/custom.db"

      - name: Build Arch Linux Package(s)
        run: |
          chown -Rh build:build $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ./new_build.sh
