name: CI

env:
  RELEASE_NAME: repo

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Download repository database
        run: |
          mkdir /repository
          cd /repository
          curl -sS -LO "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/repo/custom.db.tar.gz"
          curl -sS -LO "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/repo/custom.files.tar.gz"
          ls -lha /repository
          echo "URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/repo/custom.db"
          ln -s /repository/custom.db.tar.gz /repository/custom.db
          ln -s /repository/custom.files.tar.gz /repository/custom.files

      - name: Prepare environment
        run: |
          cat << EOF >> /etc/pacman.conf
          [custom]
          SigLevel = Optional TrustAll
          Server = file:///repository
          Server = $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/current
          EOF

          pacman-key --init
          pacman -Syu git expac devtools --noconfirm

          useradd -m -G wheel -s /bin/bash build
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/00_wheel
          chown -Rh build:build /repository

          mkdir -p /home/build/.gnupg
          echo "keyserver-options auto-key-retrieve" > /home/build/.gnupg/gpg.conf
          echo "keyserver hkps://keys.openpgp.org" >> /home/build/.gnupg/gpg.conf
          chown -Rh build:build /home/build/.gnupg/

          cd /home/build
          sudo -u build git clone https://aur.archlinux.org/aurutils
          cd aurutils
          sudo -u build makepkg -si --noconfirm
          cd ..

          dbus-uuidgen --ensure=/etc/machine-id

          sed -i "s/en_US de_DE/en_US/g" /usr/bin/mkarchroot

          CHROOT=/buildchroot
          mkdir $CHROOT
          mkarchroot -C /etc/pacman.conf $CHROOT/root base-devel

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Arch Linux Package(s)
        run: |
          chown -Rh build:build $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ./new_build.sh
          rm -f /repository/*.old /repository/{custom.db,custom.files}

      - name: Upload package artefact(s)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.RELEASE_NAME}}
          file: '/repository/*'
          file_glob: true
          overwrite: true
