name: CI

env:
  RELEASE_NAME: repo
  GPGKEY: C7F8461F3FFAFDA0

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Prepare environment
        run: |
          pacman-key --init
          pacman -Syu git expac devtools --noconfirm

          echo "GPGKEY=\"$GPGKEY\"" >> /etc/makepkg.conf

          useradd -m -G wheel -s /bin/bash build
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/00_wheel
          #chown -Rh build:build /repository

          mkdir -p /home/build/.gnupg
          echo "keyserver-options auto-key-retrieve" > /home/build/.gnupg/gpg.conf
          echo "keyserver hkps://keys.openpgp.org" >> /home/build/.gnupg/gpg.conf
          chown build:build /home/build/.gnupg/{,gpg.conf}

          dbus-uuidgen --ensure=/etc/machine-id

          sed -i "s/en_US de_DE/en_US/g" /usr/bin/mkarchroot

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download repository database
        run: |
          mkdir /repository
          cd /repository
          curl -fL --remote-name-all "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/repo/"{custom.db.tar.gz,custom.files.tar.gz} || repo-add custom.db.tar.gz
          ln -sf /repository/custom.db.tar.gz /repository/custom.db
          ln -sf /repository/custom.files.tar.gz /repository/custom.files

      - name: Import GPG Key
        run: |
          printf "%s" "$repo_key" | gpg --import
          printf "%s" "$repo_key" | pacman-key -a -
          pacman-key --lsign-key "$GPGKEY"
        env:
          repo_key: ${{ secrets.REPO_KEY }}

      - name: Build Arch Linux Package(s)
        run: |
          cat << EOF >> "$GITHUB_WORKSPACE/pacman.conf"
          [custom]
          SigLevel = Required DatabaseOptional
          Server = file:///repository
          Server = $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/repo
          EOF

          mv "$GITHUB_WORKSPACE/pacman.conf" /etc/pacman.conf
          mv "$GITHUB_WORKSPACE/aur-graph" /usr/bin/

          pacman -Syu --noconfirm

          chown -Rh build:build $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ./build.sh
          rm -f /repository/*.old{,.sig}

      - name: Upload package artefact(s)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.RELEASE_NAME}}
          file: '/repository/*'
          file_glob: true
          overwrite: true
