name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Arch Linux Package(s)
        run: |
          cat /etc/pacman.conf

          pacman-key --init
          pacman -Syu --noconfirm

          ls -lha $GITHUB_WORKSPACE
